name: Build, Push and Save

# 1. Trigger
on:
  release:
    types: [published] # Runs only when clicking "Publish release"

jobs:
  build-push-and-save:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (The builder tool)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Login to Docker Hub using GitHub Secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Part A: Push to Docker Hub
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true  # Push the image to the registry
          tags: ${{ secrets.DOCKER_USERNAME }}/backend-project:${{ github.ref_name }}

      # Part B: Save as Backup File
      
      - name: Build and Export to File
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false # Do not push, build locally only
          outputs: type=docker,dest=/tmp/my-image.tar
          tags: ${{ secrets.DOCKER_USERNAME }}/backend-project:${{ github.ref_name }}

      # Step 4: Upload the file to the GitHub Release page
      - name: Upload Artifact to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/my-image.tar